version: '3.7'
services:
  postgres:
    image: postgres:13-alpine3.18
    ports:
      - '3306:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=!qaz@wsx